version: "3"

services:
  webphp:
    image: webdevops/php-nginx-dev
    ports:
      - "8884:80"
      - "443:443"
    environment:
      WEB_DOCUMENT_INDEX: "index.html"
    volumes:
      - .:/app
